spring:
  data:
    elasticsearch:
      ssl:
        enable: ${ELASTICSEARCH_SSL_ENABLE:true}
        trust-all: ${ELASTICSEARCH_SSL_TRUST_ALL:false}
      repositories:
        enabled: false

server:
  port: 8080