spring:
  data:
    elasticsearch:
      tls: ${ELASTICSEARCH_TLS:false}
      host: ${ELASTICSEARCH_HOST:localhost}
      port: ${ELASTICSEARCH_PORT:9200}
      repositories:
        enabled: false

  jackson:
    property-naming-strategy: SNAKE_CASE