server:
  port: 8080

spring:
  profiles:
    active: local
    # prod / dev 는 엘라스틱 연결 시도, local 시 엘라스틱 연결 안함

  config:
    import: optional:file:./prography-bff/.env[.properties]

  data:
    mongodb:
      uri: ${MONGO_URI:mongodb://localhost:27017/mydb_local}
    elasticsearch:
      host: ${ELASTICSEARCH_HOST:localhost}
      port: ${ELASTICSEARCH_PORT:9200}
      user: ${ELASTICSEARCH_USER:elastic}
      password: ${ELASTICSEARCH_PASSWORD:changeme}
      ssl:
        enable: ${ELASTICSEARCH_SSL_ENABLE:true}
        # 운영 환경에서 인증서 관련해서 신경쓰지 않기 위해선 true 설정
        trust-all: ${ELASTICSEARCH_SSL_TRUST_ALL:false}
      repositories:
        enabled: false

  jackson:
    property-naming-strategy: SNAKE_CASE

  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/myapp_local}
    username: ${SPRING_DATASOURCE_USERNAME:postgres}
    password: ${SPRING_DATASOURCE_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver
  flyway:
    baselineVersion: 1
    enabled: true
    locations: classpath:db/migration
  jpa:
    open-in-view: true
    hibernate:
      ddl-auto: validate

management:
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: NEVER
  health:
    elasticsearch:
      enabled: false

kakao:
  client-id: ${KAKAO_CLIENT_ID:LOCAL_TEMP}
  redirect-uri: ${KAKAO_REDIRECT_URI:http://localhost:8080}
  client-secret: ${KAKAO_CLIENT_SECRET:LOCAL_TEMP}

naver:
  client-id: ${NAVER_CLIENT_ID:LOCAL_TEMP}
  client-secret: ${NAVER_CLIENT_SECRET:LOCAL_TEMP}

jwt:
  secret: ${JWT_SECRET:8qUY5ul8QaLGVx5PE54JBhq6jHRjGBqI}
  access-expiration: ${JWT_ACCESS_EXPIRATION:3600000}
  refresh-expiration: ${JWT_REFRESH_EXPIRATION:2592000000}