server:
  port: 8080

spring:
  config:
    import: optional:file:./prography-bff/.env[.properties]

  data:
    mongodb:
      uri: ${MONGO_URI:mongodb://localhost:27017/mydb_local}
    elasticsearch:
      host: ${ELASTICSEARCH_HOST:localhost}
      port: ${ELASTICSEARCH_PORT:9200}
      user: ${ELASTICSEARCH_USER:elastic}
      password: ${ELASTICSEARCH_PASSWORD:changeme}
      ssl:
        enable: ${ELASTICSEARCH_SSL_ENABLE:true}
        trust-all: ${ELASTICSEARCH_SSL_TRUST_ALL:false}
      repositories:
        enabled: false

  jackson:
    property-naming-strategy: SNAKE_CASE

  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/myapp_local}
    username: ${SPRING_DATASOURCE_USERNAME:postgres}
    password: ${SPRING_DATASOURCE_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver

  jpa:
    open-in-view: true
    hibernate:
      ddl-auto: create