server {
    listen 80;
    server_name api.reviewmatch.co.kr;

    location /.well-known/acme-challenge/ {
        root /var/www/html;
    }

    location / {
        return 301 https://$host$request_uri;
    }
}

server {
    listen 443 ssl;
    server_name api.reviewmatch.co.kr;

    ssl_certificate     /etc/letsencrypt/live/api.reviewmatch.co.kr/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/api.reviewmatch.co.kr/privkey.pem;

    location / {
        proxy_pass http://app-default:8080;  # 이 포트를 배포 스크립트가 sed로 교체
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
}
