name: Build & Push to Docker Hub

on:
  push:
    branches: [ deploy/bff ]
  workflow_dispatch:

env:
  IMAGE_NAME: ${{ secrets.DOCKER_USERNAME }}/reviewmatch-bff

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Set TAG (timestamp)
        id: tag
        run: echo tag=$(date '+%Y%m%d-%H%M%S') >> $GITHUB_OUTPUT

      - name: Cache Docker layers
        uses: actions/cache@v3
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-docker-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-docker-

      - name: Build & Push to Docker Hub
        run: |
          docker buildx create --use
          mkdir -p /tmp/.buildx-cache
          docker buildx build \
            --provenance=false \
            --cache-from=type=local,src=/tmp/.buildx-cache \
            --cache-to=type=local,dest=/tmp/.buildx-cache \
            --push \
            -f ./deploy/Dockerfile \
            -t ${{ env.IMAGE_NAME }}:${{ steps.tag.outputs.tag }} \
            .

      - name: SSH & Deploy to GCP
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.GCP_VM_IP }}
          username: ${{ secrets.GCP_VM_USER }}
          key: ${{ secrets.GCP_SSH_KEY }}
          envs: TAG=${{ steps.tag.outputs.tag }}
          script: |
            bash ~/prography/deploy.sh ${{ steps.tag.outputs.tag }}
